version: '3.8'
services:
  cron:
    image: localhost:32777/tv_cron
    container_name: tv_cron
    volumes:
      - ./cron/08_00:/etc/cron.08_00
      - ./cron/21_00:/etc/cron.21_00
      - ./cron/logs:/var/log/cron
      - ./tv_control:/usr/local/cron/tv_control/
      - ./tv_list/amc:/usr/local/cron/tv_list/
    restart: always
